name: VAMOS RODAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Render video
        run: npm run render

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: renders/final-video.mp4
